name = "generatedart-indexer"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
CHAIN_ID = "8453"
ETH_RPC_URL = "https://mainnet.base.org"
FACTORY_ADDRESS = "0x0000000000000000000000000000000000000000"

[[d1_databases]]
binding = "DB"
database_name = "generatedart"
database_id = "6c83d3f6-b3be-4e8d-9be2-a3274ad24e2a"

[[kv_namespaces]]
binding = "INDEXER_STATE"
id = "20884d2a97504b82822f34b6dc725e02"

# Run every minute.
[triggers]
crons = ["* * * * *"]
