import type { Env } from "./env";

function base64UrlEncode(input: ArrayBuffer | string): string {
  const bytes =
    typeof input === "string"
      ? new TextEncoder().encode(input)
      : new Uint8Array(input);
  let str = "";
  for (let i = 0; i < bytes.length; i++) str += String.fromCharCode(bytes[i]);
  return btoa(str).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function pemToArrayBuffer(pem: string): ArrayBuffer {
  const cleaned = pem
    .replace(/-----BEGIN [A-Z ]+-----/, "")
    .replace(/-----END [A-Z ]+-----/, "")
    .replace(/\s+/g, "");
  const binary = atob(cleaned);
  const buf = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) buf[i] = binary.charCodeAt(i);
  return buf.buffer;
}

async function importPrivateKey(pem: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    "pkcs8",
    pemToArrayBuffer(pem),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false,
    ["sign"]
  );
}

async function makeAppJwt(env: Env): Promise<string> {
  if (!env.GITHUB_APP_ID || !env.GITHUB_APP_PRIVATE_KEY) {
    throw new Error("github_app_not_configured");
  }
  const now = Math.floor(Date.now() / 1000);
  const header = base64UrlEncode(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const payload = base64UrlEncode(
    JSON.stringify({ iat: now - 30, exp: now + 540, iss: env.GITHUB_APP_ID })
  );
  const data = `${header}.${payload}`;
  const key = await importPrivateKey(env.GITHUB_APP_PRIVATE_KEY);
  const sig = await crypto.subtle.sign(
    "RSASSA-PKCS1-v1_5",
    key,
    new TextEncoder().encode(data)
  );
  return `${data}.${base64UrlEncode(sig)}`;
}

let cachedToken: { token: string; expiresAt: number } | null = null;

async function getInstallationToken(env: Env): Promise<string> {
  if (cachedToken && cachedToken.expiresAt - 60_000 > Date.now()) {
    return cachedToken.token;
  }
  if (!env.GITHUB_APP_INSTALLATION_ID) {
    throw new Error("github_app_installation_not_configured");
  }
  const jwt = await makeAppJwt(env);
  const res = await fetch(
    `https://api.github.com/app/installations/${env.GITHUB_APP_INSTALLATION_ID}/access_tokens`,
    {
      method: "POST",
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${jwt}`,
        "User-Agent": "GeneratedArt-API",
      },
    }
  );
  if (!res.ok)
    throw new Error(`github_installation_token_failed:${res.status}:${await res.text()}`);
  const data = (await res.json()) as { token: string; expires_at: string };
  cachedToken = { token: data.token, expiresAt: new Date(data.expires_at).getTime() };
  return data.token;
}

async function gh<T>(
  env: Env,
  method: string,
  path: string,
  body?: unknown
): Promise<T> {
  const token = await getInstallationToken(env);
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "User-Agent": "GeneratedArt-API",
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    throw new Error(`github_${method}_${path}_failed:${res.status}:${await res.text()}`);
  }
  return (await res.json()) as T;
}

export interface CreatedRepo {
  full_name: string;
  clone_url: string;
  ssh_url: string;
  html_url: string;
  default_branch: string;
}

const TEMPLATE_REPO = "art-template";

/**
 * Create a new project repo from the org template `templates/art-template`.
 * Falls back to a bare auto-init repo when the template doesn't exist yet.
 */
export async function createArtRepo(
  env: Env,
  slug: string,
  description: string
): Promise<CreatedRepo> {
  const repoName = `art-${slug}`;
  // Try template-based creation first.
  try {
    return await gh<CreatedRepo>(
      env,
      "POST",
      `/repos/${env.GITHUB_ORG}/${TEMPLATE_REPO}/generate`,
      {
        owner: env.GITHUB_ORG,
        name: repoName,
        description: description.slice(0, 350),
        include_all_branches: false,
        private: false,
      }
    );
  } catch (err) {
    if (!(err as Error).message.includes("404")) throw err;
    // Template not yet provisioned in the org — fall back to a bare repo.
    return gh<CreatedRepo>(env, "POST", `/orgs/${env.GITHUB_ORG}/repos`, {
      name: repoName,
      description: description.slice(0, 350),
      private: false,
      auto_init: true,
      has_issues: true,
      has_wiki: false,
      has_projects: false,
    });
  }
}

/** Write/replace `.github/CODEOWNERS` with the artist + curator team. */
export async function writeCodeowners(
  env: Env,
  fullName: string,
  artistGithubLogin: string
): Promise<void> {
  const content = [
    "# Auto-generated by GeneratedArt API on project creation.",
    "# Curator team owns workflow and release files; artist owns everything else.",
    "",
    `* @${artistGithubLogin} @${env.GITHUB_ORG}/curators`,
    `/.github/ @${env.GITHUB_ORG}/curators`,
    `/CODEOWNERS @${env.GITHUB_ORG}/curators`,
    "",
  ].join("\n");
  const path = ".github/CODEOWNERS";
  // Look up existing SHA if the file exists (template may already include one).
  let sha: string | undefined;
  try {
    const existing = await gh<{ sha: string }>(env, "GET", `/repos/${fullName}/contents/${path}`);
    sha = existing.sha;
  } catch {
    /* file does not exist yet */
  }
  await gh(env, "PUT", `/repos/${fullName}/contents/${path}`, {
    message: "chore: set CODEOWNERS",
    content: btoa(content),
    sha,
  });
}

/**
 * Require PR review + the validate-bundle workflow before merging into `main`.
 * Branch protection requires a paid GitHub plan for private repos; for our
 * public org repos it's free.
 */
export async function protectMainBranch(env: Env, fullName: string): Promise<void> {
  await gh(env, "PUT", `/repos/${fullName}/branches/main/protection`, {
    required_status_checks: {
      strict: true,
      contexts: ["validate-bundle"],
    },
    enforce_admins: false,
    required_pull_request_reviews: {
      required_approving_review_count: 1,
      require_code_owner_reviews: true,
    },
    restrictions: null,
    allow_force_pushes: false,
    allow_deletions: false,
  });
}

export async function createApplicationIssue(
  env: Env,
  params: {
    artistSlug: string;
    githubLogin: string;
    bio: string;
    portfolioLinks: string[];
    walletAddress?: string | null;
  }
): Promise<{ number: number; html_url: string }> {
  const body = [
    `**Slug**: \`${params.artistSlug}\``,
    `**GitHub**: @${params.githubLogin}`,
    params.walletAddress ? `**Wallet**: \`${params.walletAddress}\`` : "",
    "",
    "**Bio**",
    params.bio,
    "",
    "**Portfolio**",
    ...params.portfolioLinks.map((l) => `- ${l}`),
    "",
    "_Curators: review the artist's portfolio, then label this issue_ `approved` _to flip their role on-chain._",
  ]
    .filter(Boolean)
    .join("\n");
  return gh(env, "POST", `/repos/${env.GITHUB_ORG}/applications/issues`, {
    title: `Artist application: ${params.artistSlug}`,
    body,
    labels: ["application", "pending-review"],
  });
}
