name = "generatedart-github-bot"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
GITHUB_ORG = "GeneratedArt"
API_BASE_URL = "https://api.generatedart.com"

[[d1_databases]]
binding = "DB"
database_name = "generatedart"
database_id = "6c83d3f6-b3be-4e8d-9be2-a3274ad24e2a"

[[queues.producers]]
binding = "PIN_QUEUE"
queue = "ipfs-pin-jobs"

[env.production]
routes = [
  { pattern = "bot.generatedart.com/*", zone_name = "generatedart.com" }
]
