name: test-contracts

on:
  push:
    branches: [main]
    paths: ["contracts/**", ".github/workflows/test-contracts.yml"]
  pull_request:
    paths: ["contracts/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: contracts } }
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge install foundry-rs/forge-std --no-commit
      - run: forge install OpenZeppelin/openzeppelin-contracts --no-commit
      - run: forge install chiru-labs/ERC721A --no-commit
      - run: forge build --sizes
      - run: forge test -vv
      - run: forge coverage --report summary
